const products = [
    { id: 1, type: 'game', price: 250, img: 'https://images.unsplash.com/photo-1614726365723-49cfae96a696?q=80&w=600&auto=format&fit=crop', title_fa: 'Halo Infinite (دستیابی اسپارتان)', title_en: 'Halo Infinite Spartan Access', title_ar: 'هيلو إنفينيت' },
    { id: 2, type: 'game', price: 45, img: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop', title_fa: 'Left 4 Dead 2 Ultimate', title_en: 'Left 4 Dead 2 Ultimate', title_ar: 'ليفت 4 ديد 2' },
    { id: 3, type: 'digital', price: 80, img: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=600&auto=format&fit=crop', title_fa: 'پکیج سایبرپانک 2077', title_en: 'Cyberpunk 2077 Bundle', title_ar: 'حزينة سايبربانك' },
    { id: 4, type: 'assembly', price: 3500, img: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?q=80&w=600&auto=format&fit=crop', title_fa: 'سیستم Gaming RTX 4090 Ultimate', title_en: 'Gaming Build RTX 4090', title_ar: 'كمبيوتر جيمنج RTX 4090' },
    { id: 5, type: 'game', price: 180, img: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=600&auto=format&fit=crop', title_fa: 'Starfield: Digital Edition', title_en: 'Starfield Digital Edition', title_ar: 'ستارفيلد' }
];

const translations = {
    fa: { nav_home: "خانه", nav_games: "محصولات", nav_assembly: "مونتاژ", hero_title: "دنیای بازی‌های ۳ بعدی", hero_desc: "بهترین تجربه گیمینگ با گرافیک‌های پیشرفته.", cta_shop: "خرید کنید", cat_games: "بازی‌ها", cat_assembly: "مونتاژ", featured_products: "محصولات منتخب", btn_buy: "افزودن", service_title: "خدمات مونتاژ VR Ready", service_desc: "سیستم‌هایی آماده برای واقعیت مجازی.", btn_consult: "مشاوره", saudi_center: "مركز السعودي للاعمال", footer_desc: "پیشرو در ارائه تکنولوژی‌های نوین.", footer_links: "لینک‌ها", link_rules: "قوانین", link_warranty: "ضمانت", payment_methods: "پرداخت", checkout_title: "پرداخت امن", total_items: "اقلام:", total_price: "مبلغ:", terms_text: "قوانین را می‌پذیرم.", btn_pay: "پرداخت", error_terms: "تایید قوانین الزامی است.", toast_added: "اضافه شد", currency: "ر.س" },
    ar: { nav_home: "الرئيسية", nav_games: "المنتجات", nav_assembly: "خدمة التجميع", hero_title: "عالم الألعاب ثلاثية الأبعاد", hero_desc: "أفضل تجربة ألعاب مع رسومات متقدمة.", cta_shop: "تسوق الآن", cat_games: "ألعاب", cat_assembly: "التجميع", featured_products: "منتجات مميزة", btn_buy: "أضف", service_title: "خدمة تجميع VR", service_desc: "أنظمة جاهزة للواقع الافتراضي.", btn_consult: "استشارة", saudi_center: "مركز الأعمال السعودي", footer_desc: "رائد في تقديم التقنيات الحديثة.", footer_links: "روابط", link_rules: "قوانين", link_warranty: "ضمان", payment_methods: "الدفع", checkout_title: "دفع آمن", total_items: "العناصر:", total_price: "المبلغ:", terms_text: "أوافق على الشروط.", btn_pay: "دفع", error_terms: "يجب الموافقة على الشروط.", toast_added: "تمت الإضافة", currency: "ر.س" },
    en: { nav_home: "Home", nav_games: "Products", nav_assembly: "Assembly", hero_title: "3D Gaming World", hero_desc: "Best gaming experience with next-gen graphics.", cta_shop: "Shop Now", cat_games: "Games", cat_assembly: "Assembly", featured_products: "Featured 3D Products", btn_buy: "Add", service_title: "VR Ready Assembly", service_desc: "Systems ready for Virtual Reality.", btn_consult: "Consult", saudi_center: "Saudi Business Center", footer_desc: "Leader in modern technologies.", footer_links: "Links", link_rules: "Terms", link_warranty: "Warranty", payment_methods: "Payment", checkout_title: "Secure Checkout", total_items: "Items:", total_price: "Total:", terms_text: "I agree to terms.", btn_pay: "Pay", error_terms: "Agreeing to terms is required.", toast_added: "Added", currency: "SAR" }
};
